version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodata:/data/db

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "50051:50051"
    depends_on:
      - postgres

  service-api-tokens:
    build:
      context: ./Service-api-tokens
    ports:
      - "50052:50052"
    depends_on:
      - postgres

  video-service:
    build:
      context: ./video-service
    ports:
      - "50053:50053"
    depends_on:
      - mongodb

  main-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - service-api-tokens
      - video-service

volumes:
  pgdata:
  mongodata:
